// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { adminPageData, adminPageResponses, createItemData, createItemResponses, createUserData, createUserDirectlyData, createUserDirectlyResponses, createUserResponses, dashboardPageData, dashboardPageResponses, deleteItemData, deleteItemResponses, deleteMeData, deleteMeResponses, deleteUserData, deleteUserResponses, healthCheckData, healthCheckResponses, itemsPageData, itemsPageResponses, listItemsData, listItemsResponses, listUsersData, listUsersResponses, loginPageData, loginPageResponses, readItemData, readItemResponses, readMeData, readMeResponses, readUserData, readUserResponses, recoverPasswordData, recoverPasswordPageData, recoverPasswordPageResponses, recoverPasswordResponses, resetPasswordData, resetPasswordPageData, resetPasswordPageResponses, resetPasswordResponses, settingsPageData, settingsPageResponses, signupData, signupPageData, signupPageResponses, signupResponses, testEmailData, testEmailResponses, testTokenData, testTokenResponses, updateItemData, updateItemResponses, updateMeData, updateMeResponses, updateMyPasswordData, updateMyPasswordResponses, updateUserData, updateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * The dashboard.
 *
 * The dashboard.
 */
export const dashboardPage = <ThrowOnError extends boolean = true>(options?: Options<dashboardPageData, ThrowOnError>): RequestResult<dashboardPageResponses, unknown, ThrowOnError> => (options?.client ?? client).get<dashboardPageResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * The user administration screen.
 *
 * The user administration screen. Superuser only.
 */
export const adminPage = <ThrowOnError extends boolean = true>(options?: Options<adminPageData, ThrowOnError>): RequestResult<adminPageResponses, unknown, ThrowOnError> => (options?.client ?? client).get<adminPageResponses, unknown, ThrowOnError>({ url: '/admin', ...options });

/**
 * List items.
 *
 * List items. A superuser sees every item; everyone else sees only their own. Paginated with \`page\` and \`size\`.
 */
export const listItems = <ThrowOnError extends boolean = true>(options?: Options<listItemsData, ThrowOnError>): RequestResult<listItemsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<listItemsResponses, unknown, ThrowOnError>({ url: '/api/v1/items', ...options });

/**
 * Create an item owned by the authenticated user.
 *
 * Create an item owned by the authenticated user.
 */
export const createItem = <ThrowOnError extends boolean = true>(options: Options<createItemData, ThrowOnError>): RequestResult<createItemResponses, unknown, ThrowOnError> => (options.client ?? client).post<createItemResponses, unknown, ThrowOnError>({
    url: '/api/v1/items',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an item.
 *
 * Delete an item. Only the owner, or a superuser, may do so.
 */
export const deleteItem = <ThrowOnError extends boolean = true>(options: Options<deleteItemData, ThrowOnError>): RequestResult<deleteItemResponses, unknown, ThrowOnError> => (options.client ?? client).delete<deleteItemResponses, unknown, ThrowOnError>({ url: '/api/v1/items/{itemId}', ...options });

/**
 * Fetch one item by id.
 *
 * Fetch one item by id. Returns 404 when the item does not exist and 403 when it belongs to someone else.
 */
export const readItem = <ThrowOnError extends boolean = true>(options: Options<readItemData, ThrowOnError>): RequestResult<readItemResponses, unknown, ThrowOnError> => (options.client ?? client).get<readItemResponses, unknown, ThrowOnError>({ url: '/api/v1/items/{itemId}', ...options });

/**
 * Update an item.
 *
 * Update an item. Only the owner, or a superuser, may do so.
 */
export const updateItem = <ThrowOnError extends boolean = true>(options: Options<updateItemData, ThrowOnError>): RequestResult<updateItemResponses, unknown, ThrowOnError> => (options.client ?? client).put<updateItemResponses, unknown, ThrowOnError>({
    url: '/api/v1/items/{itemId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Verify an access token and return the user it belongs to.
 *
 * Verify an access token and return the user it belongs to.
 */
export const testToken = <ThrowOnError extends boolean = true>(options?: Options<testTokenData, ThrowOnError>): RequestResult<testTokenResponses, unknown, ThrowOnError> => (options?.client ?? client).get<testTokenResponses, unknown, ThrowOnError>({ url: '/api/v1/login/test-token', ...options });

/**
 * Send a password recovery link.
 *
 * Send a password recovery link. The response is identical whether or not the address is registered, so this endpoint cannot be used to discover which emails have accounts.
 */
export const recoverPassword = <ThrowOnError extends boolean = true>(options: Options<recoverPasswordData, ThrowOnError>): RequestResult<recoverPasswordResponses, unknown, ThrowOnError> => (options.client ?? client).post<recoverPasswordResponses, unknown, ThrowOnError>({ url: '/api/v1/password-recovery/{email}', ...options });

/**
 * Create a user without authentication.
 *
 * Create a user without authentication. Never available in production. Named distinctly from \`create_user\` on the users controller: operation ids must be unique across the whole API or the generated client ends up with a \`createUser1\`, whose number depends on declaration order.
 */
export const createUserDirectly = <ThrowOnError extends boolean = true>(options: Options<createUserDirectlyData, ThrowOnError>): RequestResult<createUserDirectlyResponses, unknown, ThrowOnError> => (options.client ?? client).post<createUserDirectlyResponses, unknown, ThrowOnError>({
    url: '/api/v1/private/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Set a new password using a recovery token.
 *
 * Set a new password using a recovery token. An expired token, a token issued for another purpose, and a token for a user that no longer exists all return the same error, so the response reveals nothing about which case applied.
 */
export const resetPassword = <ThrowOnError extends boolean = true>(options: Options<resetPasswordData, ThrowOnError>): RequestResult<resetPasswordResponses, unknown, ThrowOnError> => (options.client ?? client).post<resetPasswordResponses, unknown, ThrowOnError>({
    url: '/api/v1/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all users.
 *
 * List all users. Superuser only. Paginated with \`page\` and \`size\`. The total count is returned alongside the page so a client can render pagination controls without a second request.
 */
export const listUsers = <ThrowOnError extends boolean = true>(options?: Options<listUsersData, ThrowOnError>): RequestResult<listUsersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<listUsersResponses, unknown, ThrowOnError>({ url: '/api/v1/users', ...options });

/**
 * Create a user.
 *
 * Create a user. Superuser only. If email delivery is configured the new user is sent their credentials.
 */
export const createUser = <ThrowOnError extends boolean = true>(options: Options<createUserData, ThrowOnError>): RequestResult<createUserResponses, unknown, ThrowOnError> => (options.client ?? client).post<createUserResponses, unknown, ThrowOnError>({
    url: '/api/v1/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete the authenticated user's own account.
 *
 * Delete the authenticated user's own account. A superuser may not delete themselves; doing so could leave the system with no administrator.
 */
export const deleteMe = <ThrowOnError extends boolean = true>(options?: Options<deleteMeData, ThrowOnError>): RequestResult<deleteMeResponses, unknown, ThrowOnError> => (options?.client ?? client).delete<deleteMeResponses, unknown, ThrowOnError>({ url: '/api/v1/users/me', ...options });

/**
 * Return the currently authenticated user.
 *
 * Return the currently authenticated user.
 */
export const readMe = <ThrowOnError extends boolean = true>(options?: Options<readMeData, ThrowOnError>): RequestResult<readMeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<readMeResponses, unknown, ThrowOnError>({ url: '/api/v1/users/me', ...options });

/**
 * Update the authenticated user's own name or email.
 *
 * Update the authenticated user's own name or email.
 */
export const updateMe = <ThrowOnError extends boolean = true>(options: Options<updateMeData, ThrowOnError>): RequestResult<updateMeResponses, unknown, ThrowOnError> => (options.client ?? client).patch<updateMeResponses, unknown, ThrowOnError>({
    url: '/api/v1/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change the authenticated user's password.
 *
 * Change the authenticated user's password. Requires the current password. Returns 400 if it does not match, or if the new password is the same as the current one.
 */
export const updateMyPassword = <ThrowOnError extends boolean = true>(options: Options<updateMyPasswordData, ThrowOnError>): RequestResult<updateMyPasswordResponses, unknown, ThrowOnError> => (options.client ?? client).patch<updateMyPasswordResponses, unknown, ThrowOnError>({
    url: '/api/v1/users/me/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register a new account.
 *
 * Register a new account. Open registration: the created user is always active and never a superuser, whatever the request asks for.
 */
export const signup = <ThrowOnError extends boolean = true>(options: Options<signupData, ThrowOnError>): RequestResult<signupResponses, unknown, ThrowOnError> => (options.client ?? client).post<signupResponses, unknown, ThrowOnError>({
    url: '/api/v1/users/signup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete any user, and their items.
 *
 * Delete any user, and their items. Superuser only. A superuser may not delete their own account through this endpoint either.
 */
export const deleteUser = <ThrowOnError extends boolean = true>(options: Options<deleteUserData, ThrowOnError>): RequestResult<deleteUserResponses, unknown, ThrowOnError> => (options.client ?? client).delete<deleteUserResponses, unknown, ThrowOnError>({ url: '/api/v1/users/{userId}', ...options });

/**
 * Fetch a user by id.
 *
 * Fetch a user by id. A user may always read their own record; reading anyone else's requires superuser.
 */
export const readUser = <ThrowOnError extends boolean = true>(options: Options<readUserData, ThrowOnError>): RequestResult<readUserResponses, unknown, ThrowOnError> => (options.client ?? client).get<readUserResponses, unknown, ThrowOnError>({ url: '/api/v1/users/{userId}', ...options });

/**
 * Update any user.
 *
 * Update any user. Superuser only.
 */
export const updateUser = <ThrowOnError extends boolean = true>(options: Options<updateUserData, ThrowOnError>): RequestResult<updateUserResponses, unknown, ThrowOnError> => (options.client ?? client).patch<updateUserResponses, unknown, ThrowOnError>({
    url: '/api/v1/users/{userId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Liveness probe.
 *
 * Liveness probe. Returns \`true\` when the application is serving.
 */
export const healthCheck = <ThrowOnError extends boolean = true>(options?: Options<healthCheckData, ThrowOnError>): RequestResult<healthCheckResponses, unknown, ThrowOnError> => (options?.client ?? client).get<healthCheckResponses, unknown, ThrowOnError>({ url: '/api/v1/utils/health-check', ...options });

/**
 * Send a test email.
 *
 * Send a test email. Superuser only. Useful for checking SMTP configuration end to end. In development the message is captured by Mailpit rather than delivered.
 */
export const testEmail = <ThrowOnError extends boolean = true>(options: Options<testEmailData, ThrowOnError>): RequestResult<testEmailResponses, unknown, ThrowOnError> => (options.client ?? client).post<testEmailResponses, unknown, ThrowOnError>({
    url: '/api/v1/utils/test-email',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * The item list, server-rendered with its first page already filled in.
 *
 * The item list, server-rendered with its first page already filled in.
 */
export const itemsPage = <ThrowOnError extends boolean = true>(options?: Options<itemsPageData, ThrowOnError>): RequestResult<itemsPageResponses, unknown, ThrowOnError> => (options?.client ?? client).get<itemsPageResponses, unknown, ThrowOnError>({ url: '/items', ...options });

/**
 * The sign-in screen.
 *
 * The sign-in screen.
 */
export const loginPage = <ThrowOnError extends boolean = true>(options?: Options<loginPageData, ThrowOnError>): RequestResult<loginPageResponses, unknown, ThrowOnError> => (options?.client ?? client).get<loginPageResponses, unknown, ThrowOnError>({ url: '/login', ...options });

/**
 * The "email me a reset link" screen.
 *
 * The "email me a reset link" screen.
 */
export const recoverPasswordPage = <ThrowOnError extends boolean = true>(options?: Options<recoverPasswordPageData, ThrowOnError>): RequestResult<recoverPasswordPageResponses, unknown, ThrowOnError> => (options?.client ?? client).get<recoverPasswordPageResponses, unknown, ThrowOnError>({ url: '/recover-password', ...options });

/**
 * The "set a new password" screen, reached from the recovery email.
 *
 * The "set a new password" screen, reached from the recovery email.
 */
export const resetPasswordPage = <ThrowOnError extends boolean = true>(options: Options<resetPasswordPageData, ThrowOnError>): RequestResult<resetPasswordPageResponses, unknown, ThrowOnError> => (options.client ?? client).get<resetPasswordPageResponses, unknown, ThrowOnError>({ url: '/reset-password', ...options });

/**
 * The account settings screen.
 *
 * The account settings screen.
 */
export const settingsPage = <ThrowOnError extends boolean = true>(options?: Options<settingsPageData, ThrowOnError>): RequestResult<settingsPageResponses, unknown, ThrowOnError> => (options?.client ?? client).get<settingsPageResponses, unknown, ThrowOnError>({ url: '/settings', ...options });

/**
 * The registration screen.
 *
 * The registration screen.
 */
export const signupPage = <ThrowOnError extends boolean = true>(options?: Options<signupPageData, ThrowOnError>): RequestResult<signupPageResponses, unknown, ThrowOnError> => (options?.client ?? client).get<signupPageResponses, unknown, ThrowOnError>({ url: '/signup', ...options });
