// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ItemCreate = {
    title: string;
    description?: string | null;
};

export type ItemPublic = {
    id: string;
    title: string;
    ownerId: string;
    description?: string | null;
    createdAt?: string | null;
};

export type ItemUpdate = {
    title?: string | null;
    description?: string | null;
};

export type ItemsPublic = {
    data?: Array<ItemPublic>;
    count?: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    newPassword: string;
};

export type UpdatePassword = {
    currentPassword: string;
    newPassword: string;
};

export type UserCreate = {
    email: string;
    password: string;
    fullName?: string | null;
    isActive?: boolean;
    isSuperuser?: boolean;
};

export type UserPublic = {
    id: string;
    email: string;
    isActive: boolean;
    isSuperuser: boolean;
    fullName?: string | null;
    createdAt?: string | null;
};

export type UserRegister = {
    email: string;
    password: string;
    fullName?: string | null;
};

export type UserUpdate = {
    email?: string | null;
    password?: string | null;
    fullName?: string | null;
    isActive?: boolean | null;
    isSuperuser?: boolean | null;
};

export type UserUpdateMe = {
    email?: string | null;
    fullName?: string | null;
};

export type UsersPublic = {
    data?: Array<UserPublic>;
    count?: number;
};

export type dashboardPageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type dashboardPageResponses = {
    /**
     * dashboard_page 200 response
     */
    200: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type dashboardPageResponse = dashboardPageResponses[keyof dashboardPageResponses];

export type adminPageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin';
};

export type adminPageResponses = {
    /**
     * admin_page 200 response
     */
    200: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type adminPageResponse = adminPageResponses[keyof adminPageResponses];

export type listItemsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/api/v1/items';
};

export type listItemsResponses = {
    /**
     * list_items 200 response
     */
    200: ItemsPublic;
};

export type listItemsResponse = listItemsResponses[keyof listItemsResponses];

export type createItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items';
};

export type createItemResponses = {
    /**
     * create_item 200 response
     */
    200: {
        [key: string]: unknown;
    };
};

export type createItemResponse = createItemResponses[keyof createItemResponses];

export type deleteItemData = {
    body?: never;
    path: {
        itemId: string;
    };
    query?: never;
    url: '/api/v1/items/{itemId}';
};

export type deleteItemResponses = {
    /**
     * delete_item 200 response
     */
    200: {
        [key: string]: unknown;
    };
};

export type deleteItemResponse = deleteItemResponses[keyof deleteItemResponses];

export type readItemData = {
    body?: never;
    path: {
        itemId: string;
    };
    query?: never;
    url: '/api/v1/items/{itemId}';
};

export type readItemResponses = {
    /**
     * read_item 200 response
     */
    200: {
        [key: string]: unknown;
    };
};

export type readItemResponse = readItemResponses[keyof readItemResponses];

export type updateItemData = {
    body: ItemUpdate;
    path: {
        itemId: string;
    };
    query?: never;
    url: '/api/v1/items/{itemId}';
};

export type updateItemResponses = {
    /**
     * update_item 200 response
     */
    200: {
        [key: string]: unknown;
    };
};

export type updateItemResponse = updateItemResponses[keyof updateItemResponses];

export type testTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type testTokenResponses = {
    /**
     * test_token 200 response
     */
    200: UserPublic;
};

export type testTokenResponse = testTokenResponses[keyof testTokenResponses];

export type recoverPasswordData = {
    body?: never;
    path: {
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type recoverPasswordResponses = {
    /**
     * recover_password 200 response
     */
    200: Message;
};

export type recoverPasswordResponse = recoverPasswordResponses[keyof recoverPasswordResponses];

export type createUserDirectlyData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users';
};

export type createUserDirectlyResponses = {
    /**
     * create_user_directly 200 response
     */
    200: {
        [key: string]: unknown;
    };
};

export type createUserDirectlyResponse = createUserDirectlyResponses[keyof createUserDirectlyResponses];

export type resetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password';
};

export type resetPasswordResponses = {
    /**
     * reset_password 200 response
     */
    200: {
        [key: string]: unknown;
    };
};

export type resetPasswordResponse = resetPasswordResponses[keyof resetPasswordResponses];

export type listUsersData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/api/v1/users';
};

export type listUsersResponses = {
    /**
     * list_users 200 response
     */
    200: UsersPublic;
};

export type listUsersResponse = listUsersResponses[keyof listUsersResponses];

export type createUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type createUserResponses = {
    /**
     * create_user 200 response
     */
    200: {
        [key: string]: unknown;
    };
};

export type createUserResponse = createUserResponses[keyof createUserResponses];

export type deleteMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type deleteMeResponses = {
    /**
     * delete_me 200 response
     */
    200: {
        [key: string]: unknown;
    };
};

export type deleteMeResponse = deleteMeResponses[keyof deleteMeResponses];

export type readMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type readMeResponses = {
    /**
     * read_me 200 response
     */
    200: UserPublic;
};

export type readMeResponse = readMeResponses[keyof readMeResponses];

export type updateMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type updateMeResponses = {
    /**
     * update_me 200 response
     */
    200: UserPublic;
};

export type updateMeResponse = updateMeResponses[keyof updateMeResponses];

export type updateMyPasswordData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type updateMyPasswordResponses = {
    /**
     * update_my_password 200 response
     */
    200: {
        [key: string]: unknown;
    };
};

export type updateMyPasswordResponse = updateMyPasswordResponses[keyof updateMyPasswordResponses];

export type signupData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type signupResponses = {
    /**
     * signup 200 response
     */
    200: {
        [key: string]: unknown;
    };
};

export type signupResponse = signupResponses[keyof signupResponses];

export type deleteUserData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/v1/users/{userId}';
};

export type deleteUserResponses = {
    /**
     * delete_user 200 response
     */
    200: {
        [key: string]: unknown;
    };
};

export type deleteUserResponse = deleteUserResponses[keyof deleteUserResponses];

export type readUserData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/v1/users/{userId}';
};

export type readUserResponses = {
    /**
     * read_user 200 response
     */
    200: {
        [key: string]: unknown;
    };
};

export type readUserResponse = readUserResponses[keyof readUserResponses];

export type updateUserData = {
    body: UserUpdate;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/v1/users/{userId}';
};

export type updateUserResponses = {
    /**
     * update_user 200 response
     */
    200: {
        [key: string]: unknown;
    };
};

export type updateUserResponse = updateUserResponses[keyof updateUserResponses];

export type healthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check';
};

export type healthCheckResponses = {
    /**
     * health_check 200 response
     */
    200: boolean;
};

export type healthCheckResponse = healthCheckResponses[keyof healthCheckResponses];

export type testEmailData = {
    body: {
        emailTo?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/utils/test-email';
};

export type testEmailResponses = {
    /**
     * test_email 200 response
     */
    200: Message;
};

export type testEmailResponse = testEmailResponses[keyof testEmailResponses];

export type forbiddenPageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/forbidden';
};

export type forbiddenPageResponses = {
    /**
     * forbidden_page 200 response
     */
    200: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type forbiddenPageResponse = forbiddenPageResponses[keyof forbiddenPageResponses];

export type itemsPageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/items';
};

export type itemsPageResponses = {
    /**
     * items_page 200 response
     */
    200: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type itemsPageResponse = itemsPageResponses[keyof itemsPageResponses];

export type loginPageData = {
    body?: never;
    path?: never;
    query?: {
        error?: boolean;
    };
    url: '/login';
};

export type loginPageResponses = {
    /**
     * login_page 200 response
     */
    200: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type loginPageResponse = loginPageResponses[keyof loginPageResponses];

export type recoverPasswordPageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/recover-password';
};

export type recoverPasswordPageResponses = {
    /**
     * recover_password_page 200 response
     */
    200: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type recoverPasswordPageResponse = recoverPasswordPageResponses[keyof recoverPasswordPageResponses];

export type resetPasswordPageData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/reset-password';
};

export type resetPasswordPageResponses = {
    /**
     * reset_password_page 200 response
     */
    200: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type resetPasswordPageResponse = resetPasswordPageResponses[keyof resetPasswordPageResponses];

export type settingsPageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings';
};

export type settingsPageResponses = {
    /**
     * settings_page 200 response
     */
    200: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type settingsPageResponse = settingsPageResponses[keyof settingsPageResponses];

export type signupPageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/signup';
};

export type signupPageResponses = {
    /**
     * signup_page 200 response
     */
    200: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type signupPageResponse = signupPageResponses[keyof signupPageResponses];
